run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gosimple
    - typecheck
  disable:
    - depguard

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 5
